import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from '@/lib/axios';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

function Todo({todos}) {
//function Todo() {
  
    // const [todos, setTodos] = useState([]);
    
    // useEffect(()=>{
    //     fetchAllTodos();
    // }, []);

    // function fetchAllTodos() {
    //     axios.get('/todos').then(response=>{
    //         console.log(response);
    //         setTodos(response.data);
    //     })
    // }

    const router = useRouter();

    const fetchAllTodos = () => {
      router.replace(router.asPath);
    }

    const [name, setName] = useState('');

    const nameChange = (e) => {
        setName(e.target.value);
    }

    const submitForm = (e) => {
      e.preventDefault();
      console.log(name);
      var formData = new FormData();
      formData.append('name', name)
      formData.append('is_done', 0)
      axios.post('/todos', formData).then(response=>{
          console.log(response);
          setName('');
          fetchAllTodos();
      })
    }

    function resetTodo(){
      setName('');
      setTodoId('');
    }

    const [todoid, setTodoId] = useState('');

    function editTodo(id, index) {
      console.log(id);
      if(todos[index].id) {
        setTodoId(id);
        setName(todos[index].name);
      }
    }

    const updateTodo = () => {
      var formData = new FormData();
      formData.append('name', name)
      formData.append('is_done', 0)
      axios.put('/todos/'+todoid, formData).then(response=>{
          console.log(response);
          setName('');
          setTodoId('');
          fetchAllTodos();
      })
    }

    const deleteTodo = (id) => {
      axios.delete('/todos/'+id).then(response=>{
          console.log(response);
          fetchAllTodos();
      })
  } 

  return (
    <>
      <Head>
        <title>Next JS Todo App with Laravel API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="justify-content-center" >
        <h1 className='text-center'>Todo App</h1>
        <div className="container">
            <div className="row justify-content-center mt-5">
                <div className="col-md-6">
                    <div className="card">
                        <div className="card-header">Todo Web Application</div>

                        <div className="card-body">
                            <div className="input-group">
                                <input type="text" placeholder="Todo..." className="form-control" name="name" value={name} onChange={nameChange} />
                                &nbsp;
                                <div className="input-group-append pl-2">
                                    &nbsp;
                                    <button type="button" className="btn btn-info" onClick={submitForm}>Add</button>
                                    &nbsp;
                                    <button type="button" className="btn btn-warning" onClick={updateTodo}  >Update</button>
                                    &nbsp;
                                    <button type="button" className="btn btn-danger float-right" onClick={resetTodo} >Reset</button>
                                </div>
                            </div>
                            <table className="table table-bordered mt-4">
                                <thead>
                                    <tr>
                                      <th>Sr No</th>
                                      <th>Name</th>
                                      <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {todos.map((todo, index)=>(
                                    <tr key={todo.id}>
                                        <td> {++index } </td>
                                        <td> {todo.name} </td>
                                        <td> 
                                          <button type="button" className="btn btn-info mr-4" onClick={() => editTodo(todo.id, --index)}> Edit </button>&nbsp;
                                          <button type="button" className="btn btn-danger mr-4" onClick={() => deleteTodo(todo.id, --index)}> Delete </button>
                                         </td>
                                    </tr>
                                ))}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </main>
    </>
  )
}

//Seo > source code data add server side bcoz ctrl+u not list item display
export async function getServerSideProps(context) {
  const response = await fetch(process.env.BACKEND_API_URL+'/todos')
  const todos = await response.json()
  return { props : {todos} }
}

export default Todo;